version: '2.0'
services:

  recieve:
    build: ./consumer
    networks:
     - net_123
    depends_on:
     - queue
     - db


  queue:
    image: rabbitmq
    networks:
     - net_123
    depends_on:
     - db


  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: q12q
    networks:
     - net_123


networks:
 net_123:
    
